#!/bin/bash

set -e

# Export required environment variables
export CFLAGS="-O2 -Wno-unused-result"
export LD_LIBRARY_PATH=/usr/local/lib

# Build Radare2
echo "Building Radare2..."
cd /workspace

# Run the install script which handles configure
echo "Running installation script..."
/workspace/sys/install.sh

# Verify that config-user.mk was generated
if [ ! -f /workspace/config-user.mk ]; then
    echo "Error: config-user.mk was not generated by install.sh"
    exit 1
fi

# Create symlink if libr/config.mk doesn't exist but config-user.mk does
if [ ! -f /workspace/libr/config.mk ] && [ -f /workspace/config-user.mk ]; then
    echo "Creating symlink from config-user.mk to libr/config.mk..."
    mkdir -p /workspace/libr
    ln -sf ../config-user.mk /workspace/libr/config.mk
fi

# Verify that config.mk is now accessible
if [ ! -f /workspace/libr/config.mk ]; then
    echo "Error: libr/config.mk is not accessible"
    exit 1
fi

# Build the project
echo "Building project..."
make

echo "Configuration and build successful, running tests..."
cd /workspace
make tests

echo "Tests completed successfully!"