#!/bin/bash

# Activate Python environment
python3.11 -m venv venv
source venv/bin/activate

# Install Python dependencies
pip install --upgrade pip
pip install pyelftools ar

# Install project dependencies
tools/ci.sh unix_32bit_setup

# Build the project
tools/ci.sh unix_coverage_32bit_build

# Run the main test suite
tools/ci.sh unix_coverage_32bit_run_tests

# Build native mpy modules
tools/ci.sh native_mpy_modules_32bit_build

# Test importing .mpy generated by mpy_ld.py
tools/ci.sh unix_coverage_32bit_run_native_mpy_tests

# Print failures if any
tests/run-tests.py --print-failures