#!/bin/bash

set -e

# Export required environment variables
export CFLAGS="-O2 -Wno-unused-result"
export LD_LIBRARY_PATH=/usr/local/lib

# Build Radare2
echo "Building Radare2..."
cd /workspace

# Run the install script which handles configure
echo "Running installation script..."
/workspace/sys/install.sh

# Verify that config-user.mk was generated
if [ ! -f /workspace/config-user.mk ]; then
    echo "Error: config-user.mk was not generated by install.sh"
    exit 1
fi

# Create libr directory if it doesn't exist
mkdir -p /workspace/libr

# Create symlink from config-user.mk to libr/config.mk
# Use absolute path to ensure it resolves correctly
echo "Creating symlink from config-user.mk to libr/config.mk..."
ln -sf /workspace/config-user.mk /workspace/libr/config.mk

# Verify that config.mk is now accessible
if [ ! -f /workspace/libr/config.mk ]; then
    echo "Error: libr/config.mk is not accessible"
    exit 1
fi

# Verify the symlink points to the correct file
if [ ! -L /workspace/libr/config.mk ]; then
    echo "Warning: libr/config.mk exists but is not a symlink"
fi

# Build the project
echo "Building project..."
make

echo "Configuration and build successful, running tests..."
cd /workspace
make tests

echo "Tests completed successfully!"