#!/bin/bash

set -e

# Set non-interactive environment variables for apt-get
export DEBIAN_FRONTEND=noninteractive
export DEBCONF_NONINTERACTIVE_SEEN=true
export APTARGS="-y --no-install-recommends"

# Clone the repository (if not already present)
if [ ! -d "/workspace/micropython" ]; then
    git clone https://github.com/micropython/micropython.git /workspace/micropython
fi

cd /workspace/micropython

# Initialize submodules
git submodule update --init --recursive

# Run setup (install additional dependencies)
echo "=== Running setup ==="
bash tools/ci.sh unix_32bit_setup || true

# Build for 32-bit coverage
echo "=== Building 32-bit coverage build ==="
bash tools/ci.sh unix_coverage_32bit_build

# Run main test suite
echo "=== Running main test suite ==="
bash tools/ci.sh unix_coverage_32bit_run_tests || TEST_SUITE_FAILED=1

# Build native mpy modules
echo "=== Building native mpy modules (32-bit) ==="
bash tools/ci.sh native_mpy_modules_32bit_build || NATIVE_BUILD_FAILED=1

# Test importing .mpy generated by mpy_ld.py
echo "=== Testing native mpy imports ==="
bash tools/ci.sh unix_coverage_32bit_run_native_mpy_tests || NATIVE_TEST_FAILED=1

# Print failures if any occurred
if [ -n "$TEST_SUITE_FAILED" ] || [ -n "$NATIVE_BUILD_FAILED" ] || [ -n "$NATIVE_TEST_FAILED" ]; then
    echo "=== Printing test failures ==="
    python3 tests/run-tests.py --print-failures || true
    exit 1
fi

echo "=== All tests passed ==="
exit 0