#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status

# Activate Python environment
python3.11 -m venv venv
source venv/bin/activate

# Install Python dependencies
pip install --upgrade pip
pip install pyelftools ar

# Install project dependencies
tools/ci.sh unix_32bit_setup

# Build the project
tools/ci.sh unix_coverage_32bit_build

# Verify the build output
if [ ! -f "./ports/unix/build-coverage/micropython" ]; then
    echo "Error: micropython executable not found!"
    exit 1
fi

# Run the main test suite
tools/ci.sh unix_coverage_32bit_run_tests

# Build native mpy modules
tools/ci.sh native_mpy_modules_32bit_build

# Test importing .mpy generated by mpy_ld.py
tools/ci.sh unix_coverage_32bit_run_native_mpy_tests

# Print failures if any
tests/run-tests.py --print-failures